# Generated by Django 4.2.25 on 2025-11-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkevent',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
